
Description: Pravin MJ/Udagram Project-Bastion network host Setup

Parameters:

  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String

  InstanceType:
    Description: The instance type to use for the bastion host
    Default: t2.micro
    Type: String
    
  InstanceAMI:
    Type: String
    Default: ami-0ee02acd56a52998e
    Description: AMI of a bastion host instance to use

  SSHLocation:
    Description: Network allowed to connect using ssh to bastion host in public subnet.
    Default: 0.0.0.0/0
    Type: String

  KeyName:
    Description: Keypair for Linux bastion host
    Type: AWS::EC2::KeyPair::KeyName
    Default: BastionKeyUdagram

Resources:

  BastionSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow ssh connection to bastion host
      VpcId:
        Fn::ImportValue:
          !Sub "${EnvironmentName}-VPCID"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref SSHLocation
      SecurityGroupEgress:
      - IpProtocol: tcp
        FromPort: 0
        ToPort: 65535
        CidrIp: 0.0.0.0/0
      Tags:
        - Key: name
          Value: !Sub ${EnvironmentName} BastionHostSG

  ElasticIpBastion:
    Type: AWS::EC2::EIP
    Properties:
      Domain:
        Fn::ImportValue: !Sub ${EnvironmentName}-VPCID

  BastionAutoSG:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      LaunchConfigurationName: !Ref BastionLaunchConfig
      VPCZoneIdentifier:
        - Fn::ImportValue: !Sub ${EnvironmentName}-PUBLIC-SN1
        - Fn::ImportValue: !Sub ${EnvironmentName}-PUBLIC-SN2
      MinSize: 1
      MaxSize: 2
      DesiredCapacity: 1
      Tags:
      - Key: Name
        Value: !Sub ${EnvironmentName}-BastionAutoSG
        PropagateAtLaunch: True
    UpdatePolicy:
      AutoScalingReplacingUpdate:
        WillReplace: True

  BastionLaunchConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: !Ref InstanceAMI
      KeyName: !Ref KeyName
      IamInstanceProfile:
        Fn::ImportValue:
          !Sub ${EnvironmentName}-InstanceProfile
      SecurityGroups:
      - !Ref BastionSecGroup
      InstanceType: !Ref InstanceType
      BlockDeviceMappings:
      - DeviceName: "/dev/sdk"
        Ebs:
          VolumeSize: '10'
      UserData:
        Fn::Base64: 
          Fn::Sub:
            - |
              #!/bin/bash
              apt update
              apt install unzip
              apt-get install unzip awscli -y
              aws ssm get-parameter --name Udagram-Jumpbox-Key-Private --with-decryption --output text --query Parameter.Value > /home/ubuntu/.ssh/id_rsa
              chown ubuntu:ubuntu /home/ubuntu/.ssh/id_rsa
              chmod 700 /home/ubuntu/.ssh/id_rsa
            - EIPAllocation: !GetAtt ElasticIpBastion.AllocationId

Outputs:
  BastionPublicIPAddress:
    Description: Bastion host public IP
    Value: !Ref ElasticIpBastion
    Export:
      Name: !Sub ${EnvironmentName}-BASTION-PUBLIC-IP
  
  BastionSecurityGroupSSH:
    Description: To Allow SSH connections from the bastion host
    Value: !Ref BastionSecGroup
    Export:
      Name: !Sub ${EnvironmentName}-SSHSecurityGroup