Description: Pravin MJ/Udagram Project-S3 bucket Setup
  
Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String
  
  BucketName:
    Description: Unique name of the S3 bucket where the developers will deploy webapp
    Type: String
    Default: s3-bucket

Resources:
  Udagrams3BucketS3:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName

Outputs: 
  DataBucket:
    Value: !Ref UdagramBucketS3
    Description: Udagram bucket that stores web app zip
    Export:
      Name: !Sub ${EnvironmentName}-AppDataBucket

  DataBucketARN:
    Value: !Join ["", ["arn:aws:s3:::", !Ref "UdagramBucketS3", "/*"]]
    Export:
      Name: !Sub ${EnvironmentName}-AppDataBucketARN